branch-defaults:
  default:
    environment: django-env
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: django-app
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
